// Automatically generated by PRGA testbench generator
`timescale 1ns/1ps

// Enable post-syn if post-implementation is enabled
`ifdef PRGA_TEST_POSTIMPL
    `ifndef PRGA_TEST_POSTSYN
        `define PRGA_TEST_POSTSYN
    `endif
`endif

module prga_tb_top;

    // -----------------------------------------------------------------------
    // -- Parameters ---------------------------------------------------------
    // -----------------------------------------------------------------------
    localparam CLK_PERIOD = 10;

    // -----------------------------------------------------------------------
    // -- Signals and DUTs ---------------------------------------------------
    // -----------------------------------------------------------------------

    wire [47:0] PAD;

    wire VDD    = 1'b1;
    wire VSS    = 1'b0;
    wire VDDPST = 1'b1;
    wire VSSPST = 1'b0;


    // Inputs to DUT
    assign PAD[12] = w_test_clk;
    assign PAD[14] = w_test_reset;
    assign PAD[13] = w_test_start;

    assign PAD[15] = w_test_bcd1[3];
    assign PAD[17] = w_test_bcd1[2];
    assign PAD[19] = w_test_bcd1[1];
    assign PAD[21] = w_test_bcd1[0];

    assign PAD[25] = w_test_bcd0[3];
    assign PAD[27] = w_test_bcd0[2];
    assign PAD[29] = w_test_bcd0[1];
    assign PAD[31] = w_test_bcd0[0];

    // Outputs from DUT
    assign w_test_ready = PAD[0];
    assign w_test_done_tick = PAD[2];
    assign w_test_bin[6] = PAD[4];
    assign w_test_bin[5] = PAD[6];
    assign w_test_bin[4] = PAD[8];
    assign w_test_bin[3] = PAD[10];
    assign w_test_bin[2] = PAD[16];
    assign w_test_bin[1] = PAD[18];
    assign w_test_bin[0] = PAD[20];

    chip_top i_chip (
        .PAD(PAD),
        .VDD(VDD),
        .VSS(VSS),
        .VDDPST(VDDPST),
        .VSSPST(VSSPST)
    );


    // Testbench ctrl
    reg f_tb_clk, f_tb_rst;
    wire w_tb_pass, w_tb_fail, w_tb_prog_done;

    // Logging
    reg [31:0] f_tb_verbosity, f_tb_max_cycle, f_tb_cycle_cnt;

    // -- Test ---------------------------------------------------------------
    // Signals
    wire w_test_clk;
    wire w_test_reset;
    wire w_test_start;
    wire [3:0] w_test_bcd1;
    wire [3:0] w_test_bcd0;
    wire w_test_ready;
    wire w_test_done_tick;
    wire [6:0] w_test_bin;

    // Tester
    basic i_tester (
        .tb_clk(f_tb_clk)
        ,.tb_rst(f_tb_rst)
        ,.tb_pass(w_tb_pass)
        ,.tb_fail(w_tb_fail)
        ,.tb_prog_done(w_tb_prog_done)
        ,.tb_verbosity(f_tb_verbosity)
        ,.tb_cycle_cnt(f_tb_cycle_cnt)
        ,.clk(w_test_clk)
        ,.reset(w_test_reset)
        ,.start(w_test_start)
        ,.bcd1(w_test_bcd1)
        ,.bcd0(w_test_bcd0)
        ,.ready(w_test_ready)
        ,.done_tick(w_test_done_tick)
        ,.bin(w_test_bin)
        );

    // -- Behavioral Model ---------------------------------------------------
    // Signals
    wire w_behav_ready;
    wire w_behav_done_tick;
    wire [6:0] w_behav_bin;

    // DUT
    bcd2bin i_behav (
        .clk(w_test_clk)
        ,.reset(w_test_reset)
        ,.start(w_test_start)
        ,.bcd1(w_test_bcd1)
        ,.bcd0(w_test_bcd0)
        ,.ready(w_behav_ready)
        ,.done_tick(w_behav_done_tick)
        ,.bin(w_behav_bin)
        );

    // -- Post-Synthesis Model -----------------------------------------------
`ifdef PRGA_TEST_POSTSYN
    // Signals
    wire w_postsyn_ready;
    wire w_postsyn_done_tick;
    wire [6:0] w_postsyn_bin;

    // DUT
    postsyn i_postsyn (
        .clk(w_test_clk)
        ,.reset(w_test_reset)
        ,.start(w_test_start)
        ,.bcd1(w_test_bcd1)
        ,.bcd0(w_test_bcd0)
        ,.ready(w_postsyn_ready)
        ,.done_tick(w_postsyn_done_tick)
        ,.bin(w_postsyn_bin)
        );
`endif  // `ifdef PRGA_TEST_POSTSYN

    // -- Post-Implementation Model ------------------------------------------
`ifdef PRGA_TEST_POSTIMPL
    // Signals
    wire w_impl_ready;
    wire w_impl_done_tick;
    wire [6:0] w_impl_bin;

    // DUT
    implwrap i_postimpl (
        .tb_clk(f_tb_clk)
        ,.tb_rst(f_tb_rst)
        ,.tb_prog_done(w_tb_prog_done)
        ,.tb_verbosity(f_tb_verbosity)
        ,.tb_cycle_cnt(f_tb_cycle_cnt)
        ,.clk(w_test_clk)
        ,.reset(w_test_reset)
        ,.start(w_test_start)
        ,.bcd1(w_test_bcd1)
        ,.bcd0(w_test_bcd0)
        ,.ready(w_impl_ready)
        ,.done_tick(w_impl_done_tick)
        ,.bin(w_impl_bin)
        );
`else   // `ifdef PRGA_TEST_POSTIMPL
    assign w_tb_prog_done = 1'b1;
`endif  // `ifdef PRGA_TEST_POSTIMPL

    // -----------------------------------------------------------------------
    // -- Testbench Control Logic --------------------------------------------
    // -----------------------------------------------------------------------

    initial begin
        if (!$value$plusargs("verbosity=%d", f_tb_verbosity)) begin
            f_tb_verbosity = 1;
        end
        
        if (!$value$plusargs("max_cycle=%d", f_tb_max_cycle)) begin
            f_tb_max_cycle = 100_000; // 100K cycles
        end

        if (f_tb_verbosity >= 1)
            $display("[INFO] Max cycle count: %d", f_tb_max_cycle);

        f_tb_clk = 1'b0;
        f_tb_rst = 1'b0;
        f_tb_cycle_cnt = 0;

        #(CLK_PERIOD * 1.25) f_tb_rst = 1'b1;
        #(CLK_PERIOD * 10) f_tb_rst = 1'b0;
    end

    // Testbench clock generator
    always #(CLK_PERIOD / 2.0) f_tb_clk = ~f_tb_clk;

    // Cycle count tracking
    always @(posedge f_tb_clk) begin
        if (f_tb_rst) begin
            f_tb_cycle_cnt <= 0;
        end else begin
            f_tb_cycle_cnt <= f_tb_cycle_cnt + 1;
            if (f_tb_verbosity >= 1 && f_tb_cycle_cnt % 1_000 == 0)
                $display("[INFO] %3dK cycles passed", f_tb_cycle_cnt / 1_000);

            if (w_tb_fail) begin
                $display();
                $display("[INFO] ++=========================++");
                $display("[INFO] ||       TEST FAILED       ||");
                $display("[INFO] ++=========================++");
                $display();
                $finish;
            end else if (w_tb_pass) begin
                $display();
                $display("[INFO] ++=========================++");
                $display("[INFO] ||       TEST PASSED       ||");
                $display("[INFO] ++=========================++");
                $display();
                $finish;
            end

            if (f_tb_cycle_cnt >= f_tb_max_cycle) begin
                $display("[ERROR] Max cycle count reached, killing simulation");
                $finish;
            end
        end
    end

    // -----------------------------------------------------------------------
    // -- Wiring -------------------------------------------------------------
    // -----------------------------------------------------------------------
`ifdef PRGA_TEST_POSTIMPL
    assign w_test_ready = w_impl_ready;
    assign w_test_done_tick = w_impl_done_tick;
    assign w_test_bin = w_impl_bin;
`else   // `ifdef PRGA_TEST_POSTIMPL
`ifdef PRGA_TEST_POSTSYN
    assign w_test_ready = w_postsyn_ready;
    assign w_test_done_tick = w_postsyn_done_tick;
    assign w_test_bin = w_postsyn_bin;
`else   // `ifdef PRGA_TEST_POSTSYN
    assign w_test_ready = w_behav_ready;
    assign w_test_done_tick = w_behav_done_tick;
    assign w_test_bin = w_behav_bin;
`endif  // `ifdef PRGA_TEST_POSTSYN
`endif  // `ifdef PRGA_TEST_POSTIMPL

endmodule