#!/usr/bin/env bash
# =============================================================================
# pack_artifact.sh — build the PUBLIC artifact-evaluation tarball for CacheFlex
#
#   Output: /tmp/cacheflex_artifact_<YYYYMMDD>.tar.gz   (override with --out)
#           — always written OUTSIDE the repo so it is never packed into itself.
#
# INTERNAL TOOL — this script is itself excluded from the package it builds.
# It packs ONLY this repository (the tree it lives in), never a sibling dev tree.
#
# MODES (no default action — prevents an accidental full pack while gem5
# campaigns are still writing into results dirs):
#   --list             stream the would-be-archived member list to stdout
#                      (pipe through `head`/`grep`; tar is killed by SIGPIPE)
#   --print-excludes   print the fully-expanded exclusion list and exit
#   --estimate         du-based uncompressed size estimate of the include set
#                      (metadata walk only; safe while runs are in flight)
#   --check            run the complete packaging pre-flight without creating
#                      an archive
#   --build            create the tarball. HARD-FAILS the pre-flight if any
#                      canonical reference input is missing, incomplete, or has
#                      a broken symlink. RUN ONLY AFTER THE SIMULATION CAMPAIGN
#                      HAS FINISHED.
#
# WHAT IS KEPT:
#   - all source, kernels, paper experiment build/run scripts, the four
#     data-driven plotters, exactly two project-owned usage documents
#     (README.md + SETUP.md), plus gem5's upstream license files
#   - only the canonical reference subsets consumed by the paper plotters:
#       Fig 2: results_fig2_n2048_headh0 + results_spm_fused_n2048_headh0 (paper shape 256x2048x2048)
#       Fig 7: results_headh0
#       Fig 8: flat best/ pool containing the 12 selected ladder rows
#       Fig 9: simulation_results/{vl4,vl16}
#     Per-cell heavyweight files are stripped (fs/, citations.bib, config.json);
#     stats.txt, config.ini, stdout.log, stdout.txt and *.log are kept.
#     NEVER add -h/--dereference to the tar invocation.
#
# WHAT IS EXCLUDED:
#   - results/generated/** and results/campaign_*/** everywhere (regenerable
#     best/sweep output and author-side in-flight campaign staging)
#   - gem5/build, gem5/util/m5/build, tools/ (regenerated by scons /
#     scripts/setup_tools.sh — internet requirement documented in SETUP.md)
#   - kernel binaries (bin/, bin_gem5/, bin_qemu/, *.o, *_enc.s), __pycache__/,
#     *.pyc, m5out*, and internal/dev-only bookkeeping (see §1a)
#
# NOTE on tar pattern semantics (GNU tar default matching: wildcards ON,
# wildcards-match-slash ON, not anchored): member names start with "./", so a
# leading-"./" pattern is anchored to the repo root; a bare component like
# "__pycache__" matches at any depth; a pattern like "*/results/generated"
# matches that path at any depth (its "*" crosses "/").
# =============================================================================
set -euo pipefail

# Bind packaging and its pre-flight checks to this artifact tree.
unset CACHEFLEX_ROOT BEST_JSON GENERATED_DIR RESULTS_DIR OUTPUT_DIR GEM5 GEM5_SE

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"                    # this repo (DST) — the ONLY tree packed
OUT="/tmp/cacheflex_artifact_$(date +%Y%m%d).tar.gz"    # OUTSIDE the repo

MODE=""
OUT_SET=0
while [[ $# -gt 0 ]]; do
    case "$1" in
        --list|--print-excludes|--estimate|--check|--build)
            if [[ -n "$MODE" ]]; then
                echo "ERROR: choose exactly one mode; got --$MODE and $1" >&2
                exit 2
            fi
            MODE="${1#--}"
            shift
            ;;
        --out)
            if (( OUT_SET )); then
                echo "ERROR: --out may be specified only once" >&2
                exit 2
            fi
            if [[ $# -lt 2 || "$2" == --* ]]; then
                echo "ERROR: --out requires a file path" >&2
                exit 2
            fi
            OUT="$2"
            OUT_SET=1
            shift 2
            ;;
        *) echo "usage: $0 --list | --print-excludes | --estimate | --check | --build [--out FILE]" >&2
           exit 2 ;;
    esac
done
if [[ -z "$MODE" ]]; then
    echo "usage: $0 --list | --print-excludes | --estimate | --check | --build [--out FILE]" >&2
    echo "(no default mode: gem5 campaigns may still be writing; see header)" >&2
    exit 2
fi
if (( OUT_SET )) && [[ "$MODE" != build ]]; then
    echo "ERROR: --out is valid only with --build" >&2
    exit 2
fi

# The archive must live OUTSIDE the repo it packs. Resolve --out to an
# absolute physical path first so relative paths (e.g. --out subdir/x.tar.gz
# or ../..-tricks) cannot bypass the check.
OUT="$(cd "$(dirname "$OUT")" 2>/dev/null && pwd -P)/$(basename "$OUT")" || {
    echo "ERROR: --out parent directory does not exist: $OUT" >&2; exit 2; }
case "$OUT" in
    "$ROOT"/*|"$ROOT") echo "ERROR: --out must be OUTSIDE the repo ($ROOT); got: $OUT" >&2; exit 2 ;;
esac
if [[ "$MODE" == build ]]; then
    # Do not follow a caller-supplied output symlink back into the repository,
    # and do not silently overwrite an earlier artifact from the same day.
    [[ ! -L "$OUT" ]] || {
        echo "ERROR: refusing symlink archive output: $OUT" >&2
        exit 2
    }
    [[ ! -e "$OUT" ]] || {
        echo "ERROR: archive output already exists; choose a new --out path: $OUT" >&2
        exit 2
    }
fi

# -----------------------------------------------------------------------------
# 1. EXCLUDES
# -----------------------------------------------------------------------------
EX=()

# 1a. Internal / dev-only bookkeeping (never ship). Most are already absent
#     after migration; kept defensive because .gitignore does not survive tar.
EX+=(
    './*_FINDINGS.md'
    './CODE_REVIEW_INTERNAL.md'
    './HANDOFF.md'
    './MERGE_*_NOTES.md'
    './EXPERIMENTS.md'
    './ARTIFACT_MANIFEST.md'
    './CITATION.cff'
    './PROVENANCE.json'                             # contains host/path metadata
    './FREEZE_SOURCE_MAP.json'                      # internal source/install receipt
    './STAGING_MANIFEST.sha256'                    # internal atomic-install seal
    './MIGRATION_MANIFEST.json'
    './MIGRATION_REPORT.md'
    # './docs' is SHIPPED: docs/CLAIMS.md is the kernel-provenance and
    # comparison-policy disclosure the artifact must carry.
    './gem5/docs'                                   # upstream documentation; not needed to build/run
    './gem5/ext/googletest/docs'
    './gem5/ext/googletest/googlemock/docs'
    './gem5/ext/googletest/googletest/docs'
    './gem5/ext/ply/doc'
    './gem5/ext/pybind11/docs'
    './gem5/ext/pybind11/.github'
    './gem5/src/doc'
    './gem5/.devcontainer'
    './gem5/.github'
    # './experiments/*.md' and './kernels/*.md' are SHIPPED: with GNU tar
    # wildcards-match-slash semantics those patterns would drop the required
    # provenance docs (experiments/end2end/UNFUSED_REGENERATION.md,
    # experiments/end2end/table4/README.md, kernels/end2end/src/fair/README.md)
    # — the only .md files under those trees.
    './scripts/*.md'
    './spm_tools/*.md'
    './tests/*.md'
    # NOTE: './gem5/*.md' is intentionally NOT excluded — gem5/README.md is a
    # clean-build input (embedded into m5/info.py by gem5/src/SConscript).
    './gem5/*.rst'
    './.claude'
    './gem5env.sh'                                  # developer-sandbox env (machine-specific)
    './gem5/configs/deprecated/example/se_multicore.py'
    './scripts/pack_artifact.sh'                    # this script (internal)
    './backups'
)

# 1b. Development-only experiments that do not produce a result shown in the
#     paper. They remain in the authors' development tree but are
#     deliberately outside the AE artifact and its supported run interface.
EX+=(
    './experiments/hardware_prefetcher'
    './experiments/flash_attention'
    './experiments/loop_order'
    './experiments/pure_gemm_compare'
    './experiments/shared_bandwidth'
    './experiments/belady'
    './experiments/multicore'
    './experiments/gemm_shape'
)

# 1c. Regenerable build products and caches (any depth)
EX+=(
    'bin'                # kernel binaries — rebuilt by build.sh
    'bin_gem5'
    'bin_qemu'
    '*.o'
    '*_enc.s'
    '__pycache__'
    '*.pyc'
    'm5out*'             # stray gem5 default outdirs
    '*.trace'
    './kernels/gemm/software_alternatives/v7g_mt_weak_cres_bc.s'  # generated asm
    './kernels/llama_bench_spm/07_out_proj_spm_vl4.s'             # empty unused stub
)

# 1d. Heavy regenerable trees
EX+=(
    './gem5/build'                 # rebuilt by scons build/ARM/gem5.opt (SETUP.md step 5)
    './gem5/util/m5/build'         # rebuilt by scons (m5op)
    './gem5/compile_commands.json' # regenerated by the gem5 build
    './tools'                      # ARM toolchain + QEMU + conda — re-downloaded by setup_tools.sh
    '.venv'                        # local Python environments — rebuilt from requirements.txt
    './tests/out_smoke_gem5'       # regenerated by tests/smoke_gem5.sh
)

# 1e. GENERATED and campaign-staging results everywhere; REFERENCE results are
#     kept. Excludes experiments/<e>/results/generated and results/campaign_*
#     at any depth; results/reference/** is untouched.
EX+=(
    '*/results/generated'
    './results/generated'
    '*/results/campaign_*'
    './results/campaign_*'
)

# 1f. Legacy drivers and derived figures from superseded configurations.
#     The three run_kc_sweep_vl*.sh helpers are intentionally retained: they are
#     the canonical implementation behind vl_length/run.sh --sweep.
EX+=(
    # Paper outputs are always regenerated under results/generated/.  Keeping
    # old root-level renders would create a second, potentially stale truth.
    './experiments/capacity_motivation/fig2_real.pdf'
    './experiments/capacity_motivation/fig2_real.png'
    './experiments/capacity_motivation/fig2_data.json'
    './experiments/vl_length/fig7_real.pdf'
    './experiments/vl_length/fig7_real.png'
    './experiments/vl_length/fig7_data.json'
    './experiments/software_alternatives/fig8_real.pdf'
    './experiments/software_alternatives/fig8_real.png'
    './experiments/software_alternatives/fig8_data.json'
    './experiments/capacity_motivation/run_fig2_cache_orig.sh'
    './experiments/capacity_motivation/run_fig2_cache_h0.sh'
    './experiments/capacity_motivation/run_motivation_cap_bw_v2.sh'
    './experiments/capacity_motivation/run_motivation_spm_fused.sh'
    './experiments/capacity_motivation/run_spm_fused_h0.sh'
    './experiments/capacity_motivation/run_vls_proxy.sh'
    './experiments/capacity_motivation/plot_motivation_final_v4.py'
    './experiments/capacity_motivation/fig2_real_orig.*'
    './experiments/capacity_motivation/fig2_real_h0.*'
    './experiments/capacity_motivation/fig_combined.*'
    './experiments/vl_length/*f?ir*'
    './experiments/vl_length/run_m8_head0.sh'
    './experiments/vl_length/run_rerun_best.sh'
    './experiments/vl_length/run_tile_probe.sh'
    './experiments/vl_length/run_v3_nodbg.sh'
    './experiments/vl_length/fig7_real_paper.*'
    './experiments/vl_length/fig7_real_m8h0.*'
    './experiments/end2end/scripts/rerun_best.sh'
    './experiments/end2end/scripts/rerun_best_h0.sh'
    './experiments/end2end/fig9_real_orig.*'
    './experiments/end2end/fig9_real_h0.*'
    './experiments/software_alternatives/runners/run_cell.sh'
    './experiments/software_alternatives/runners/run_cell_h0.sh'
    './experiments/software_alternatives/twosize_ladder/controlled_size.sh'
    './experiments/software_alternatives/twosize_ladder/run_cell_hwpfoff.sh'
    './experiments/software_alternatives/twosize_ladder/ladder_data*.json'
    './experiments/software_alternatives/twosize_ladder/fig_ladder_live.*'
    './experiments/software_alternatives/twosize_ladder/g2048_headh0'
    './experiments/software_alternatives/twosize_ladder/g2048_hh0full'
    './experiments/software_alternatives/twosize_ladder/w3_headh0'
    './experiments/software_alternatives/twosize_ladder/w3_hh0full'
    './experiments/software_alternatives/l1swpf/matrix'
    './experiments/software_alternatives/l2-swpf-non-t-load/matrix'
    './experiments/software_alternatives/l2-swpf-non-t-load/matrix_smoke_postmerge'
)

# 1g. Canonical-reference allowlist. Any present top-level child other than the
#     named canonical pools (and MANIFEST.sha256) is excluded automatically.
#     This is deliberately an allowlist so a newly copied legacy result tree
#     cannot silently enter a future archive.
exclude_noncanonical_reference_children() {
    local exp="$1"; shift
    local allowed=" MANIFEST.sha256 $* "
    local ref="$ROOT/experiments/$exp/results/reference"
    local child name
    [[ -d "$ref" ]] || return 0
    while IFS= read -r -d '' child; do
        name="$(basename "$child")"
        case "$allowed" in
            *" $name "*) ;;
            *) EX+=( "./experiments/$exp/results/reference/$name" ) ;;
        esac
    done < <(find "$ref" -mindepth 1 -maxdepth 1 -print0)
}

# Root-level compatibility links are subject to the same allowlist. Excluding a
# legacy target but retaining its link would create a dangling archive member.
exclude_noncanonical_reference_links() {
    local exp="$1"; shift
    local allowed=" $* "
    local base="$ROOT/experiments/$exp"
    local link name target
    [[ -d "$base" ]] || return 0
    while IFS= read -r -d '' link; do
        target="$(readlink "$link")"
        [[ "$target" == *results/reference/* ]] || continue
        name="$(basename "$link")"
        case "$allowed" in
            *" $name "*) ;;
            *) EX+=( "./experiments/$exp/$name" ) ;;
        esac
    done < <(find "$base" -mindepth 1 -maxdepth 1 -type l -print0)
}

exclude_noncanonical_results_links() {
    local exp="$1"; shift
    local allowed=" $* "
    local base="$ROOT/experiments/$exp/results"
    local link name
    [[ -d "$base" ]] || return 0
    while IFS= read -r -d '' link; do
        name="$(basename "$link")"
        case "$allowed" in
            *" $name "*) ;;
            *) EX+=( "./experiments/$exp/results/$name" ) ;;
        esac
    done < <(find "$base" -mindepth 1 -maxdepth 1 -type l -print0)
}

# Only results/reference is public.  The name-based campaign/generated rules
# above remain useful global defenses, while this per-experiment allowlist also
# catches a future ad-hoc diagnostic directory with a different name.
exclude_noncanonical_results_children() {
    local exp="$1"
    local base="$ROOT/experiments/$exp/results"
    local child name
    [[ -d "$base" ]] || return 0
    while IFS= read -r -d '' child; do
        name="$(basename "$child")"
        [[ "$name" == reference ]] \
            || EX+=( "./experiments/$exp/results/$name" )
    done < <(find "$base" -mindepth 1 -maxdepth 1 -print0)
}

exclude_noncanonical_reference_children capacity_motivation \
    results_fig2_n2048_headh0 results_spm_fused_n2048_headh0
exclude_noncanonical_reference_children vl_length results_headh0
exclude_noncanonical_reference_children software_alternatives best
exclude_noncanonical_reference_children end2end simulation_results

exclude_noncanonical_reference_links capacity_motivation \
    results_fig2_n2048_headh0 results_spm_fused_n2048_headh0
exclude_noncanonical_reference_links vl_length results_headh0
exclude_noncanonical_reference_links software_alternatives
exclude_noncanonical_reference_links end2end

exclude_noncanonical_results_links capacity_motivation
exclude_noncanonical_results_links vl_length
exclude_noncanonical_results_links software_alternatives
exclude_noncanonical_results_links end2end

exclude_noncanonical_results_children capacity_motivation
exclude_noncanonical_results_children vl_length
exclude_noncanonical_results_children software_alternatives
exclude_noncanonical_results_children end2end

# Root allowlist: a newly created author-side file must not silently become a
# public archive member.  Subtree contents remain governed by the scoped
# rules above and the semantic pre-flight below.
exclude_unapproved_root_children() {
    local allowed=" .gitignore LICENSE THIRD_PARTY_NOTICES README.md SETUP.md requirements.txt run_all.sh setup_env.sh docs experiments gem5 kernels results scripts spm_tools tests "
    local child name
    while IFS= read -r -d '' child; do
        name="$(basename "$child")"
        case "$allowed" in
            *" $name "*) ;;
            *) EX+=( "./$name" ) ;;
        esac
    done < <(find "$ROOT" -mindepth 1 -maxdepth 1 -print0)
}
exclude_unapproved_root_children

# -----------------------------------------------------------------------------
# 2. PER-CELL HEAVYWEIGHT STRIP — scoped to KEPT reference cells only.
#    (gem5/tests/**/fs and gem5/test*/configs are real gem5 source and survive.)
#    No plotter/parser reads fs/, citations.bib or config.json
#    (audit_results.py reads config.ini). Covers one-level result cells and the
#    three-level end2end
#    results/reference/simulation_results/<vl>/<cell> layout.
# -----------------------------------------------------------------------------
for f in fs citations.bib config.json; do
    EX+=( "*/results/reference/*/$f" )
    EX+=( "*/results/reference/*/*/$f" )
    EX+=( "*/results/reference/*/*/*/$f" )
    EX+=( "./experiments/software_alternatives/twosize_ladder/*/$f" )
    EX+=( "./gem5/test/$f" )                     # stray smoke-run outputs inside gem5/
done

TAR_EX=()
for p in "${EX[@]}"; do TAR_EX+=( "--exclude=$p" ); done

# -----------------------------------------------------------------------------
# 3. --build PRE-FLIGHT — the four paper plotters and their reference inputs.
#    Any missing tool, missing/empty reference input,
#    unparseable paper-grid cell, or broken reference
#    symlink is a HARD failure (exit 1).
#
#      1. experiments/capacity_motivation/plot_fig2_real.py            (Fig 2)
#      2. experiments/vl_length/plot_fig7_real.py                      (Fig 7)
#      3. experiments/software_alternatives/twosize_ladder/make_fig_ladder_live.py (Fig 8)
#      4. experiments/end2end/scripts/plot_fig9_real.py               (Fig 9)
#    Only the canonical results/reference children named in §1g are accepted.
#    There is no fallback to a flat or legacy result layout.
# -----------------------------------------------------------------------------
REQUIRED_WORKFLOW_FILES=(
    experiments/capacity_motivation/plot_fig2_real.py
    experiments/vl_length/plot_fig7_real.py
    experiments/software_alternatives/twosize_ladder/make_fig_ladder_live.py
    experiments/end2end/scripts/plot_fig9_real.py
    scripts/compare_results.py
    scripts/render_reference.sh
    run_all.sh
)

nonempty_dir() { [[ -d "$1" && -n "$(find "$1" -mindepth 1 -print -quit 2>/dev/null)" ]]; }

# Print the allowlisted top-level reference directories for one experiment.
canonical_reference_dirs() {
    case "$1" in
        capacity_motivation)
            printf '%s\n' \
                results_fig2_n2048_headh0 \
                results_spm_fused_n2048_headh0 ;;
        vl_length)
            printf '%s\n' results_headh0 ;;
        software_alternatives)
            printf '%s\n' best ;;
        end2end)
            printf '%s\n' simulation_results/vl4 simulation_results/vl16 ;;
        *)
            echo "ERROR: no canonical reference allowlist for experiment: $1" >&2
            return 2 ;;
    esac
}

require_canonical_reference_dirs() {
    local exp="$1" d fail=0
    while IFS= read -r d; do
        [[ -n "$d" ]] || continue
        if ! nonempty_dir "$ROOT/experiments/$exp/results/reference/$d"; then
            echo "FAIL: canonical reference missing/empty: experiments/$exp/results/reference/$d" >&2
            fail=1
        fi
    done < <(canonical_reference_dirs "$exp")
    return "$fail"
}

# Every Figure 8 cell frozen in best.json must have exactly one complete
# directory in the canonical flat best pool.
verify_software_best_coverage() {
    python3 - "$ROOT/experiments/software_alternatives/best.json" \
        "$ROOT/experiments/software_alternatives/results/reference" <<'PY'
import json
import configparser
import pathlib
import re
import shlex
import sys

best_path = pathlib.Path(sys.argv[1])
ref = pathlib.Path(sys.argv[2])
if not best_path.is_file():
    print(f"FAIL: Fig. 8 best.json missing: {best_path}", file=sys.stderr)
    raise SystemExit(1)

def complete(path):
    required = ("config.ini", "stats.txt", "stdout.txt")
    return path.is_dir() and all(
        (path / filename).is_file() and (path / filename).stat().st_size > 0
        for filename in required
    )

cells = json.loads(best_path.read_text())["cells"]
expected_names = {cell["name"] for cell in cells}
if len(expected_names) != len(cells):
    print("FAIL: duplicate Figure 8 best.json cell name", file=sys.stderr)
    raise SystemExit(1)
pool = ref / "best"
actual_names = {path.name for path in pool.iterdir() if path.is_dir()} if pool.is_dir() else set()
problems = []
if actual_names != expected_names:
    problems.append(
        f"canonical cell set differs from best.json: "
        f"missing={sorted(expected_names - actual_names)}, "
        f"extra={sorted(actual_names - expected_names)}"
    )

bad_log = re.compile(
    r"\b(?:fatal|panic|segmentation fault|core dumped)\b|"
    r"\bassert(?:ion)?\b[^\n]{0,256}\bfailed\b|"
    r"simulated exit code not 0|validation failed|SELF_CHECK (?:FAIL|SKIP)|"
    r"\[DBG\]",
    re.I,
)
for cell in cells:
    name = cell["name"]
    path = pool / name
    if not complete(path):
        problems.append(f"{name}: missing/empty config.ini, stats.txt, or stdout.txt")
        continue
    log = (path / "stdout.txt").read_text(errors="ignore")
    if "Exiting @ tick" not in log:
        problems.append(f"{name}: no clean gem5 exit")
    if bad_log.search(log):
        problems.append(f"{name}: crash/assert marker")
    if not re.search(r"[0-9.]+\s+GFLOPS", log):
        problems.append(f"{name}: no GFLOPS result")

    cfg = configparser.ConfigParser(strict=False)
    if not cfg.read(path / "config.ini"):
        problems.append(f"{name}: unparseable config.ini")
        continue
    checks = {
        ("system.cpu.dcache", "mshrs"): "8",
        ("system.cpu.isa", "sve_vl_se"): "16",
        ("system.tol2bus", "header_latency"): "0",
    }
    checks.update({
        ("system.cpu", "spmloadports"): "1",
        ("system.cpu", "spmstoreports"): "1",
    })
    for (section, key), wanted in checks.items():
        got = cfg.get(section, key, fallback=None)
        if got != wanted:
            problems.append(f"{name}: {section}.{key}={got}, expected {wanted}")

    argv = shlex.split(cfg.get("system.cpu.workload", "cmd", fallback=""))
    wanted_args = shlex.split(cell["args"])
    if not argv or pathlib.Path(argv[0]).name != pathlib.Path(cell["binary"]).name:
        problems.append(f"{name}: workload binary does not match best.json")
    # best.json records M N K KC MC.  Figure 8 runners invoke the
    # microkernel as M K N n_iter KC MC.
    expected_argv = [
        wanted_args[0],
        wanted_args[2],
        wanted_args[1],
        "1",
        wanted_args[3],
        wanted_args[4],
    ]
    if argv[1:] != expected_argv:
        problems.append(
            f"{name}: recorded args {argv[1:]} do not match "
            f"best.json {wanted_args}"
        )

    receipts = {
        "RUN_ENV.txt": cell.get("env") or "none",
        "RUNNER_USED.txt": cell["runner"],
        "BINARY_USED.txt": cell["binary"],
    }
    for filename, wanted in receipts.items():
        receipt = path / filename
        got = receipt.read_text().strip() if receipt.is_file() else None
        if got != wanted:
            problems.append(f"{name}: {filename}={got!r}, expected {wanted!r}")
    hashes = path / "BINARIES.sha256"
    if not hashes.is_file():
        problems.append(f"{name}: missing BINARIES.sha256")
    else:
        lines = hashes.read_text().splitlines()
        if len(lines) != 2 or any(
            re.fullmatch(r"[0-9a-f]{64}  [^/\s][^\s]*", line) is None
            for line in lines
        ):
            problems.append(f"{name}: malformed/non-relative BINARIES.sha256")

for problem in problems:
    print(f"FAIL: Figure 8 canonical receipt: {problem}", file=sys.stderr)
raise SystemExit(bool(problems))
PY
}

verify_best_result_receipts() {
    python3 - "$ROOT" "$@" <<'PY'
import configparser
import json
import pathlib
import re
import shlex
import sys

root = pathlib.Path(sys.argv[1])
experiments = sys.argv[2:] or (
    "capacity_motivation",
    "vl_length",
    "end2end",
)
known_experiments = {
    "capacity_motivation",
    "vl_length",
    "end2end",
}
problems = []


unknown_experiments = set(experiments) - known_experiments
if unknown_experiments:
    problems.append(
        f"unknown best-result experiment(s): {sorted(unknown_experiments)}"
    )


target_params = {
    "system.cpu[0].dcache.mshrs": "mshrs",
    "system.tol2bus.header_latency": "header_latency",
    "system.cpu[0].isa[0].sve_vl_se": "vl",
    "system.cpu[0].spmLoadPorts": "spm_load_ports",
    "system.cpu[0].spmStorePorts": "spm_store_ports",
}
config_locations = {
    "mshrs": ("system.cpu.dcache", "mshrs"),
    "header_latency": ("system.tol2bus", "header_latency"),
    "vl": ("system.cpu.isa", "sve_vl_se"),
    "spm_load_ports": ("system.cpu", "spmloadports"),
    "spm_store_ports": ("system.cpu", "spmstoreports"),
}
block_config = {
    "vl4": {
        "vl": "4",
        "spm_load_ports": "2",
        "spm_store_ports": "1",
    },
    "vl16": {
        "vl": "16",
        "spm_load_ports": "1",
        "spm_store_ports": "1",
    },
}


def unsigned(value, label):
    if not isinstance(value, str) or re.fullmatch(r"[0-9]+", value) is None:
        problems.append(f"{label}: expected an unsigned integer, got {value!r}")
        return None
    return str(int(value))


def gem5_spm_defaults():
    """Read defaults used only by Fig. 2 cache-only cells from shipped gem5."""
    source = root / "gem5" / "src" / "cpu" / "o3" / "BaseO3CPU.py"
    try:
        text = source.read_text()
    except OSError as error:
        problems.append(f"cannot read gem5 SPM-port defaults: {error}")
        return {}
    defaults = {}
    for source_name, key in (
        ("spmLoadPorts", "spm_load_ports"),
        ("spmStorePorts", "spm_store_ports"),
    ):
        matches = re.findall(
            rf"^\s*{source_name}\s*=\s*Param\.Unsigned\(\s*([0-9]+)\s*,",
            text,
            re.M,
        )
        if len(matches) != 1:
            problems.append(
                f"{source.relative_to(root)}: expected exactly one numeric "
                f"default for {source_name}, found {len(matches)}"
            )
            continue
        defaults[key] = str(int(matches[0]))
    return defaults


spm_defaults = gem5_spm_defaults()


def gem5_extra_params(cell, label):
    try:
        tokens = shlex.split(cell.get("gem5_extra") or "")
    except (TypeError, ValueError) as error:
        problems.append(f"{label}: invalid gem5_extra: {error}")
        return {}
    params = {}
    index = 0
    while index < len(tokens):
        token = tokens[index]
        assignment = None
        if token == "-P":
            index += 1
            if index >= len(tokens):
                problems.append(f"{label}: gem5_extra ends with bare -P")
                break
            assignment = tokens[index]
        elif token.startswith("-P") and len(token) > 2:
            assignment = token[2:]
        if assignment is not None:
            if "=" not in assignment:
                problems.append(
                    f"{label}: malformed gem5 parameter {assignment!r}"
                )
            else:
                raw_key, raw_value = assignment.split("=", 1)
                key = target_params.get(raw_key)
                if key is not None:
                    value = unsigned(
                        raw_value.strip(),
                        f"{label}: gem5_extra {raw_key}",
                    )
                    if key in params:
                        problems.append(
                            f"{label}: duplicate gem5_extra parameter {raw_key}"
                        )
                    elif value is not None:
                        params[key] = value
        index += 1
    return params


def expected_config(experiment, cell):
    label = f"{experiment}/{cell.get('name', '<unnamed>')}"
    params = gem5_extra_params(cell, label)
    expected = {
        "mshrs": "8",
        "header_latency": "0",
    }
    for fixed in ("mshrs", "header_latency"):
        if fixed in params and params[fixed] != expected[fixed]:
            problems.append(
                f"{label}: gem5_extra {fixed}={params[fixed]}, "
                f"required {expected[fixed]}"
            )

    block = cell.get("block")
    if experiment == "end2end":
        if block is None:
            problems.append(f"{label}: missing configuration block")
            return None
        if block not in block_config:
            problems.append(f"{label}: unknown configuration block {block!r}")
            return None
        derived = block_config[block]
        for key, value in derived.items():
            if key in params and params[key] != value:
                problems.append(
                    f"{label}: gem5_extra {key}={params[key]} conflicts "
                    f"with block {block} ({value})"
                )
        expected.update(derived)
        return expected
    if block is not None:
        problems.append(
            f"{label}: unexpected configuration block outside end2end"
        )
        return None

    vl = params.get("vl")
    if vl not in {"4", "8", "16"}:
        problems.append(
            f"{label}: gem5_extra must specify VL as one of 4, 8, or 16"
        )
        return None
    expected["vl"] = vl

    explicit_ports = {
        key: params[key]
        for key in ("spm_load_ports", "spm_store_ports")
        if key in params
    }
    if len(explicit_ports) == 2:
        expected.update(explicit_ports)
    elif explicit_ports:
        problems.append(
            f"{label}: gem5_extra must specify both SPM load/store ports"
        )
        return None
    elif (
        experiment == "capacity_motivation"
        and pathlib.Path(cell.get("binary", "")).name == "v1_fused"
        and not cell.get("name", "").startswith("v3fused_")
    ):
        # These cache-only Figure 2 cells intentionally omit SPM overrides.
        # Their expected values are the simulator defaults, read above from
        # the exact gem5 source that is included in the artifact.
        if set(spm_defaults) != {"spm_load_ports", "spm_store_ports"}:
            problems.append(f"{label}: cannot derive gem5 SPM-port defaults")
            return None
        expected.update(spm_defaults)
    else:
        problems.append(
            f"{label}: gem5_extra does not specify both SPM load/store ports"
        )
        return None
    return expected


def read_config(path, label):
    config = configparser.ConfigParser(interpolation=None, strict=True)
    try:
        with path.open() as stream:
            config.read_file(stream)
    except (OSError, configparser.Error) as error:
        problems.append(f"{label}: unparseable config.ini: {error}")
        return None
    return config


def check_recorded_config(experiment, cell, config):
    label = f"{experiment}/{cell['name']}"
    expected = expected_config(experiment, cell)
    if expected is None:
        return
    for key, wanted in expected.items():
        section, option = config_locations[key]
        got = config.get(section, option, fallback=None)
        if got is not None:
            got = got.strip()
        if got != wanted:
            problems.append(
                f"{label}: {section}.{option}={got!r}, expected {wanted!r}"
            )


def check_cell(experiment, cell, pool, log_path):
    run_dir = pool / cell["name"]
    required = (run_dir / "config.ini", run_dir / "stats.txt", log_path)
    missing = [
        path.name
        for path in required
        if not path.is_file() or path.stat().st_size == 0
    ]
    if missing:
        problems.append(
            f"{experiment}/{cell['name']}: missing/empty {', '.join(missing)}"
        )
        return
    config = read_config(
        run_dir / "config.ini",
        f"{experiment}/{cell['name']}",
    )
    if config is None:
        return
    check_recorded_config(experiment, cell, config)
    try:
        argv = shlex.split(
            config.get("system.cpu.workload", "cmd", fallback="")
        )
    except ValueError as error:
        problems.append(
            f"{experiment}/{cell['name']}: malformed workload command: {error}"
        )
        argv = []
    expected = shlex.split(cell["args"])
    if len(argv) < 1 or argv[1:] != expected:
        problems.append(
            f"{experiment}/{cell['name']}: recorded args {argv[1:]} "
            f"do not match best.json {expected}"
        )
    expected_binary = pathlib.Path(cell["binary"]).name
    actual_binary = pathlib.Path(argv[0]).name if argv else None
    if actual_binary != expected_binary:
        problems.append(
            f"{experiment}/{cell['name']}: recorded binary {actual_binary} "
            f"does not match best.json {expected_binary}"
        )


for experiment in experiments:
    if experiment not in known_experiments:
        continue
    exp = root / "experiments" / experiment
    try:
        best = json.loads((exp / "best.json").read_text())
        cells = best["cells"]
        if not isinstance(cells, list):
            raise TypeError("'cells' is not a list")
    except (OSError, ValueError, KeyError, TypeError) as error:
        problems.append(f"{experiment}: invalid best.json: {error}")
        continue
    names = [cell.get("name") for cell in cells if isinstance(cell, dict)]
    if len(names) != len(cells) or any(not name for name in names):
        problems.append(f"{experiment}: every best.json cell needs a name")
        continue
    identities = [
        (cell.get("block"), cell["name"])
        if experiment == "end2end"
        else cell["name"]
        for cell in cells
    ]
    if len(set(identities)) != len(identities):
        problems.append(f"{experiment}: duplicate best.json cell identity")
        continue
    ref = exp / "results" / "reference"
    for cell in cells:
        name = cell["name"]
        if experiment == "capacity_motivation":
            pool_name = (
                "results_spm_fused_n2048_headh0"
                if name.startswith("v3fused_")
                else "results_fig2_n2048_headh0"
            )
            pool = ref / pool_name
            log_path = pool / f"{name}.log"
        elif experiment == "vl_length":
            pool = ref / "results_headh0"
            log_path = pool / f"{name}.log"
        else:
            pool = ref / "simulation_results" / cell["block"]
            log_path = pool / name / "stdout.log"
        check_cell(experiment, cell, pool, log_path)

        if log_path.is_file() and "[DBG]" in log_path.read_text(errors="ignore"):
            problems.append(
                f"{experiment}/{name}: debug trace remains in canonical log"
            )

for problem in problems:
    print(f"FAIL: canonical result receipt mismatch: {problem}", file=sys.stderr)
raise SystemExit(bool(problems))
PY
}

verify_canonical_interconnect() {
    python3 - "$ROOT" <<'PY'
import pathlib
import re
import sys

root = pathlib.Path(sys.argv[1])
allow = {
    "capacity_motivation": (
        "results_fig2_n2048_headh0",
        "results_spm_fused_n2048_headh0",
    ),
    "vl_length": ("results_headh0",),
    "software_alternatives": ("best",),
    "end2end": ("simulation_results/vl4", "simulation_results/vl16"),
}
expected = {
    "frontend_latency": "1",
    "header_latency": "0",
    "forward_latency": "1",
    "response_latency": "1",
}
problems = []
for experiment, pools in allow.items():
    ref = root / "experiments" / experiment / "results" / "reference"
    for pool in pools:
        configs = sorted((ref / pool).rglob("config.ini"))
        if not configs:
            problems.append(f"{experiment}/{pool}: no config.ini files")
            continue
        for path in configs:
            text = path.read_text(errors="ignore")
            match = re.search(
                r"^\[system\.tol2bus\]\n(.*?)(?=^\[)",
                text,
                re.S | re.M,
            )
            section = match.group(1) if match else ""
            bad = []
            for key, wanted in expected.items():
                found = re.search(rf"^{key}=(.*)$", section, re.M)
                actual = found.group(1).strip() if found else None
                if actual != wanted:
                    bad.append(f"{key}={actual}")
            if bad:
                problems.append(
                    f"{path.relative_to(root)}: {', '.join(bad)}"
                )

for problem in problems:
    print(f"FAIL: non-canonical interconnect config: {problem}", file=sys.stderr)
raise SystemExit(bool(problems))
PY
}

verify_archive_symlinks() {
    # Audit the exact member set selected by TAR_EX, not just reference pools.
    # Symlinks remain symlinks in the archive; require every one to be relative,
    # resolve inside this repository, and point to another selected member.
    local -A members=()
    local -a links=()
    local member path target resolved relative
    local fail=0

    while IFS= read -r member; do
        member="${member%% -> *}"
        member="${member%/}"
        [[ "$member" == ./* || "$member" == "." ]] || continue
        members["$member"]=1
        path="$ROOT/${member#./}"
        [[ -L "$path" ]] && links+=( "$member" )
    done < <(
        cd "$ROOT"
        tar "${TAR_EX[@]}" -cvf /dev/null . 2>/dev/null
    )

    for member in "${links[@]}"; do
        path="$ROOT/${member#./}"
        target="$(readlink -- "$path")"
        if [[ "$target" == /* ]]; then
            echo "FAIL: absolute archive symlink: $member -> $target" >&2
            fail=1
            continue
        fi
        if ! resolved="$(readlink -e -- "$path")"; then
            echo "FAIL: broken archive symlink: $member -> $target" >&2
            fail=1
            continue
        fi
        case "$resolved" in
            "$ROOT")
                relative="."
                ;;
            "$ROOT"/*)
                relative="./${resolved#"$ROOT"/}"
                ;;
            *)
                echo "FAIL: archive symlink escapes repository: $member -> $target" >&2
                fail=1
                continue
                ;;
        esac
        if [[ -z "${members[$relative]+selected}" ]]; then
            echo "FAIL: archive symlink target is excluded: $member -> $target" >&2
            fail=1
        fi
    done
    return "$fail"
}

verify_archive_member_types() {
    # A public source/results archive has no reason to contain devices, FIFOs,
    # sockets, or other special filesystem objects.
    local member path
    local fail=0
    while IFS= read -r member; do
        member="${member%% -> *}"
        member="${member%/}"
        [[ "$member" == ./* || "$member" == "." ]] || continue
        path="$ROOT/${member#./}"
        if [[ -L "$path" || -f "$path" || -d "$path" ]]; then
            continue
        fi
        echo "FAIL: unsupported archive member type: $member" >&2
        fail=1
    done < <(
        cd "$ROOT"
        tar "${TAR_EX[@]}" -cvf /dev/null . 2>/dev/null
    )
    return "$fail"
}

verify_no_packaged_binary_magic() {
    # Extension filters are convenient but not authoritative.  Inspect the
    # exact selected regular-file set so an accidentally copied executable,
    # object, library, or WebAssembly module cannot be sealed into a
    # code-and-results-only archive under an innocuous filename.
    (
        cd "$ROOT"
        tar "${TAR_EX[@]}" -cvf /dev/null . 2>/dev/null
    ) | python3 /dev/fd/3 "$ROOT" 3<<'PY'
import pathlib
import struct
import sys

root = pathlib.Path(sys.argv[1])
hits = []
seen = set()
fixed_magic = {
    b"\x7fELF": "ELF",
    b"!<arch>\n": "ar archive",
    b"!<thin>\n": "thin ar archive",
    b"\x00asm": "WebAssembly",
    b"\xfe\xed\xfa\xce": "Mach-O",
    b"\xce\xfa\xed\xfe": "Mach-O",
    b"\xfe\xed\xfa\xcf": "Mach-O",
    b"\xcf\xfa\xed\xfe": "Mach-O",
    b"\xca\xfe\xba\xbe": "Mach-O universal",
    b"\xbe\xba\xfe\xca": "Mach-O universal",
    b"\xca\xfe\xba\xbf": "Mach-O universal",
    b"\xbf\xba\xfe\xca": "Mach-O universal",
}

for line in sys.stdin:
    member = line.rstrip("\n").split(" -> ", 1)[0]
    if member.startswith("./"):
        member = member[2:]
    if not member:
        continue
    path = root / member
    if path in seen or path.is_symlink() or not path.is_file():
        continue
    seen.add(path)
    try:
        with path.open("rb") as stream:
            head = stream.read(4096)
            kind = next(
                (
                    label
                    for magic, label in fixed_magic.items()
                    if head.startswith(magic)
                ),
                None,
            )
            # A valid PE header can legally sit beyond the DOS stub bytes read
            # above. Seek to e_lfanew instead of assuming it is within 4 KiB.
            if kind is None and head.startswith(b"MZ") and len(head) >= 64:
                offset = struct.unpack_from("<I", head, 0x3C)[0]
                if offset <= path.stat().st_size - 4:
                    stream.seek(offset)
                    if stream.read(4) == b"PE\0\0":
                        kind = "PE executable"
    except OSError:
        continue
    if kind is not None:
        hits.append((member, kind))

for member, kind in hits[:100]:
    print(f"FAIL: packaged binary magic ({kind}): {member}", file=sys.stderr)
if len(hits) > 100:
    print(f"FAIL: ... and {len(hits) - 100} more binary files", file=sys.stderr)
if hits:
    raise SystemExit(1)
print(f"OK: {len(seen)} packaged regular files contain no binary object/executable magic.")
PY
}

preflight() {
    local fail=0 p
    for p in "${REQUIRED_WORKFLOW_FILES[@]}"; do
        [[ -f "$ROOT/$p" ]] || { echo "FAIL: required workflow file missing: $p" >&2; fail=1; }
    done
    # gem5/README.md is a clean-build input (embedded into m5/info.py by
    # gem5/src/SConscript); assert it exists AND survives the archive filters.
    if ! ( cd "$ROOT"; tar "${TAR_EX[@]}" -cvf /dev/null ./gem5/README.md 2>/dev/null ) \
            | grep -q 'gem5/README\.md'; then
        echo "FAIL: gem5/README.md must ship (clean gem5 build input)" >&2; fail=1
    fi
    local exp
    for exp in capacity_motivation vl_length software_alternatives end2end; do
        require_canonical_reference_dirs "$exp" || fail=1
    done
    python3 "$ROOT/scripts/reference_integrity.py" check --root "$ROOT" || fail=1
    verify_software_best_coverage || fail=1
    # End-to-end has an explicit legacy-measured reference profile.  Its exact
    # membership/config checks, available receipts, and narrow mode/exit
    # exceptions live in reference_integrity.py and plot_fig9_real.py.  Keep
    # those validators authoritative instead of duplicating the policy here.
    verify_best_result_receipts capacity_motivation vl_length || fail=1
    verify_canonical_interconnect || fail=1
    python3 "$ROOT/experiments/vl_length/audit_results.py" \
        "$ROOT/experiments/vl_length/results/reference/results_headh0" || fail=1
    python3 "$ROOT/experiments/end2end/scripts/plot_fig9_real.py" \
        --check "$ROOT/experiments/end2end/results/reference" || fail=1

    # Broken-symlink audit is limited to the canonical reference allowlist.
    local d l
    for exp in capacity_motivation vl_length software_alternatives end2end; do
        while IFS= read -r d; do
            [[ -d "$ROOT/experiments/$exp/results/reference/$d" ]] || continue
            while IFS= read -r -d '' l; do
                readlink -e "$l" >/dev/null \
                    || { echo "FAIL: broken canonical reference symlink: ${l#"$ROOT"/}" >&2; fail=1; }
            done < <(find "$ROOT/experiments/$exp/results/reference/$d" -type l -print0)
        done < <(canonical_reference_dirs "$exp")
    done

    verify_archive_symlinks || fail=1
    verify_archive_member_types || fail=1
    verify_no_packaged_binary_magic || fail=1

    # Scan exactly the members selected by this script, so excluded campaign
    # staging and developer-only files cannot create false positives.
    if ! (
        cd "$ROOT"
        tar "${TAR_EX[@]}" -cvf /dev/null . 2>/dev/null
    ) | python3 "$ROOT/scripts/reference_integrity.py" privacy --root "$ROOT"; then
        fail=1
    fi
    return $fail
}

# -----------------------------------------------------------------------------
# 4. Modes
# -----------------------------------------------------------------------------
case "$MODE" in
  print-excludes)
    printf '%s\n' "${EX[@]}"
    ;;
  list)
    # streams member names; safe to `| head -50` (tar dies on SIGPIPE).
    # No -h: symlinks are archived as symlinks.
    cd "$ROOT"
    exec tar "${TAR_EX[@]}" -cvf /dev/null . 2>/dev/null
    ;;
  estimate)
    # Metadata-only walk (no file contents read): du over the include set.
    # Reuse the scoped exclusions verbatim. In particular, do not add a global
    # "fs" basename exclusion: gem5/tests/gem5/fs is real simulator source and
    # is intentionally part of the archive.
    cd "$ROOT"
    DU_EX=()
    for p in "${EX[@]}"; do DU_EX+=( "--exclude=$p" ); done
    echo "Uncompressed include-set size (apparent bytes):"
    du -sb "${DU_EX[@]}" . | awk '{printf "  %.2f GiB (%d bytes)\n", $1/1073741824, $1}'
    echo "The packed size depends on the final reference logs; confirm it with"
    echo "the final --build output."
    ;;
  check)
    echo ">>> Pre-flight: verifying the paper reference inputs ..."
    preflight
    echo ">>> Pre-flight OK."
    ;;
  build)
    echo ">>> Pre-flight: verifying the four paper reference inputs ..."
    if ! preflight; then
        echo ">>> ABORT: reference inputs incomplete or a reference symlink is broken." >&2
        echo ">>>        Populate every canonical results/reference directory, regenerate" >&2
        echo ">>>        its MANIFEST.sha256, and rerun this command." >&2
        exit 1
    fi
    echo ">>> Pre-flight OK. Building $OUT"
    echo ">>> REMINDER: run only after ALL gem5 campaigns have finished —"
    echo ">>>           in-flight runs produce torn stats.txt in the archive."
    GZ=(gzip)
    command -v pigz >/dev/null 2>&1 && GZ=(pigz)
    OUT_DIR="$(dirname "$OUT")"
    OUT_BASE="$(basename "$OUT")"
    PARTIAL="$OUT_DIR/.${OUT_BASE}.partial.$$"
    if [[ -e "$PARTIAL" || -L "$PARTIAL" ]]; then
        echo "ERROR: temporary archive path already exists: $PARTIAL" >&2
        exit 2
    fi
    cleanup_partial_archive() {
        rm -f -- "$PARTIAL"
    }
    trap cleanup_partial_archive EXIT HUP INT TERM
    cd "$ROOT"
    # normalize ownership/uname so the archive carries no host identity
    tar "${TAR_EX[@]}" --owner=0 --group=0 --numeric-owner \
        -I "${GZ[0]}" -cf "$PARTIAL" .
    # Validate the completed stream before atomically publishing it at --out.
    tar -tzf "$PARTIAL" >/dev/null
    # Hard-link publication is atomic and fails if another process created
    # --out after the initial absence check; unlike mv, it cannot clobber it.
    ln -- "$PARTIAL" "$OUT"
    rm -f -- "$PARTIAL"
    trap - EXIT HUP INT TERM
    echo ">>> done:"
    ls -lh "$OUT"
    sha256sum "$OUT"
    echo ">>> Post-pack checklist:"
    echo "    1. tar -tzf on a scratch machine; confirm NO internal doc names appear"
    echo "       (check for review notes, handoff notes, and developer-only metadata)."
    echo "    2. Unpack fresh; follow SETUP.md, then README.md."
    echo "    3. Re-render paper Figures 2, 7, 8, and 9 from the shipped reference results."
    echo "    4. Confirm the anonymous archive contains no author, host, or local-path metadata."
    ;;
esac
